### PR TITLE
Fix deprecations and enable CI testing on nightly

### PR DESCRIPTION
**Pull request by omus**

### CODE REVIEW

**Comment by omus** [comment]
You'll need to enable AppVeyor builds for this repository to use those changes.

**Comment by omus** [comment]
Bump

**Comment by samoconnor** [comment]
Hi @omus ,
Thanks for this, and I'm sorry that it escaped my attention.
I don't intend to support 0.6 and 0.7 simultaneously for the packages in my AWS stack (SymDict, XMLDict, InfoZIP, Retry and AWS*). My intention is to wait until 0.7 is released, then update the packages and drop 0.6 from REQUIRE.

I the case of this package I'm hoping that the new NamedTuple stuff will make it obsolete.

I'm happy to merge this now, but I may not tag it, or I may drop 0.6 from REQUIRE (and remove Compat) before tagging. Are you using this in a package directly? or just as a dependancy of AWS*?

**Comment by omus** [comment]
I'm just using this package as part of AWS*. I can understand waiting before tagging Julia 0.7 changes but could you tag a new revision of this package which supports Julia 0.6 without the `typealias` deprecation? Say: d0aedcfca26bbe3f90aec51440aa462c5a1d26ed?

**Comment by samoconnor** [comment]
Well, this is a tiny simple package. I don't see any problem tagging as-is since you've already gone to the effort of making it work on 0.7.
Thanks!

**Comment by samoconnor** [comment]
See https://github.com/samoconnor/SymDict.jl/commit/3f7dd4e3bb5f0620b1dbf9a5221393665e152bcf

**Comment by omus** [comment]
Nice find. I'm glad the `eval` could be removed.

**Pull request merged**
